services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ./data:/data
    ports:
      - 5000:5000
    
  frontend: 
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
