services:
  backend:
    image: $REGISTRY_URL/$GITLAB_PROJECT_PATH/backend
    #image: sp-backend:latest
    volumes:
      - ./data:/app/data
    ports:
      - 5000:5000

  frontend:
    image: $REGISTRY_URL/$GITLAB_PROJECT_PATH/frontend
    #image: sp-frontend:latest
    ports:
      - 80:80