FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y tzdata && \
    ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime && \
    echo "Europe/Moscow" > /etc/timezone && \
    dpkg-reconfigure -f noninteractive tzdata && \
    apt-get clean

WORKDIR /backend_rocket_bot

COPY ./backend_rocket_bot .
    
RUN pip install --no-cache-dir -r requirements.txt
CMD ["uvicorn", "main:bot_app", "--host", "0.0.0.0", "--port", "5000"]
#docker build -f docker/Dockerfile.rocket_bot -t sp-rocket .